### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by bigardone** [saschatimme/elm-phoenix#1]
Hi! 
First of all thanks for creating this package, it looks pretty awesome.
I want to refactor one of my projects so I can use it, but it seems the package is not available via the `elm package install` command, and checking out your example app, it is importing it using a partial file path. How can I install it? 
Cheers!

**Comment by saschatimme** [comment]
Hey,

the package is not yet released on elm package, because I'm still gathering some feedback, but it should (hopefully) be released in the next week or so.

In the meantime there are two ways to install the package:
1. You just copy the files in your local project.
2. You clone the project and specify the relative path to the project in the `elmBrunch` part of the the [`brunch-config.js`](https://github.com/saschatimme/elm-phoenix/blob/master/example/brunch-config.js) (probably the cleaner / better solution)

I hope this helps and let me hear if you have any problems or ideas for improvements :)

**Comment by bigardone** [comment]
Hey, 
I finally managed to install it downloading the files and adding them into a `vendor` folder inside my project. Here's the repo where I'm using it https://github.com/bigardone/phoenix-and-elm/tree/phoenix-channels :)
I have a question, though. The only thing I'm missing is to leave a channel manually. I've found a `leaveMessage` function in the `ChannelHelpers` module, but I'm not quite sure how to use it. I'd like to use it for example when a user navigates to a different route, and I want him to disconnect from the current channel he is connected to. How would you do that?
Cheers!

**Comment by saschatimme** [comment]
You simply don't include the channel in your channel list anymore :) (Probably I should make it clearer that it is this simple.) If you want to do something after you left a channel you can set an `onLeave` callback on the channel.

Here is the code snippet in the example application:

``` elm
subscriptions : Model -> Sub Msg
subscriptions model =
    case model.state of
        JoiningLobby ->
            Phoenix.connect socket [ lobby model.userName ]

        JoinedLobby ->
            Phoenix.connect socket [ lobby model.userName ]

        _ ->
            Phoenix.connect socket []
```

If `model.state` is not `JoiningLobby` or `JoiningLobby` you will leave the `room:lobby` channel, but keep the socket connection open.

**Comment by bigardone** [comment]
Oh, now I get it!
I really love the approach you've taken for this library. My favorite elm/phoenix client so far, congrats!
Cheers!

**Comment by dustinfarris** [comment]
@saschatimme is this ready for elm package yet?

**Comment by saschatimme** [comment]
@dustinfarris  The package would be ready for elm package but it's not in my hands (effect-managers need to be whitelisted). I started a [discussion](https://groups.google.com/forum/?nomobile=true#!topic/elm-dev/MD5r5P3Tl7Q) on elm-dev but so far nothing went from there.

So if anyone wants to see this on elm package you should advocate for it in the elm-dev discussion.
