### ISSUE TITLE
Would it be possible to move the phoenix example to another repo?

### ISSUE THREAD

**Issue by banglashi** [saschatimme/elm-phoenix#14]
Hi @saschatimme 
When I use your module to deploy via edeliver and distillery I have problems while compiling because it also goes over the example project. I haven't found a way to omit/exclude the path from the compiler. If you have any suggestion how to avoid this problem let me know, otherwise would it be possible to move the phoenix example to another repo? Thanks

**Comment by dustinfarris** [comment]
I have not had this problem.

Here is my brunch-config https://gist.github.com/dustinfarris/9aeb9a5617c57aed1ba761cc66b71c48

**Comment by saschatimme** [comment]
You could also take a look at [this issue](https://github.com/saschatimme/elm-phoenix/issues/7).

**Comment by banglashi** [comment]
Thanks for the links. I decided to upgrade to 1.3 and now the deployments work fine.
