### ISSUE TITLE
Why this package is not on package.elm-lang.org yet?

### ISSUE THREAD

**Issue by douglascorrea** [saschatimme/elm-phoenix#15]
As described by Evan post on `elm-dev` list, `native/kernel` code are not allowed to be on package.elm-lang.org except those on @elm-lang, but this library do not use any `native/kernel` code. It is is *pure* Elm.

So, what is stopping this to be on package.elm-lang.org?

**Comment by dustinfarris** [comment]
I have mentioned in elm-dev.  Waiting on @evancz

**Comment by saschatimme** [comment]
At the moment for `effect managers` apply the same rules as for `native`.
