### ISSUE TITLE
Using with multiple Elm entry points

### ISSUE THREAD

**Issue by whodidthis** [saschatimme/elm-phoenix#20]
What would be a good way to use elm-phoenix in a non-SPA environment where multiple Elm programs are embedded onto the page? If multiple programs would want to use a channel or two is it possible for them to share the socket?

**Comment by opsb** [comment]
elm-phoenix is built on top of https://github.com/elm-lang/websocket which doesn't allow for sharing connections between multiple Elm apps. Unfortunately I don't see an easy way to add support for this scenario at the moment.

**Comment by whodidthis** [comment]
Thanks, I'll keep this in mind
