### ISSUE TITLE
Merge in elm_phoenix_example

### ISSUE THREAD

**Issue by opsb** [saschatimme/elm-phoenix#23]
It would be good to update the example app in this repo according to https://github.com/jur0/elm_phoenix_example. @jur0 is there any reason not to just replace the current example app with the version you put together? (I haven't had a chance to review the differences yet)

**Comment by jur0** [comment]
It's pretty much the same as the example you keep in this repo apart from the "user management" which is handled by Presence now.

Also, as we discussed the last time, it'd be good to provide a decoder for the `PresenceState`.
