### ISSUE TITLE
Channel.onJoin should be fired before Channel.on

### ISSUE THREAD

**Issue by saschatimme** [saschatimme/elm-phoenix#26]
@dustinfarris reported that at the moment it can happen that a `Msg` from `Channel.onJoin` arrives **after** a `Msg` from `Channel.on`.

### My investigation so far:
Currently there is a simple dispatch on each incoming message of the websocket (https://github.com/saschatimme/elm-phoenix/blob/master/src/Phoenix.elm#L537). So I think if one pushes a message to the client before the join reply (this should be possible since the socket connection is already established) they could be arrive out of order.

**Comment by cjen07** [comment]
I think if you have `send self() {:after_join, state}` in `join` function in your channel and broadcast any msg in `handle_info({:after_join, state}, socket)`, the msg will definitely arrive before that from `onJoin`.

**Comment by saschatimme** [comment]
Will close this for now, since one could avoid the problem with changes on the elixir side.
