### ISSUE TITLE
No message is ever dispatched when the server is not available.

### ISSUE THREAD

**Issue by alpacaaa** [saschatimme/elm-phoenix#27]
Thanks a lot for this package!

I can't seem to find a way to check whether the initial connection to the server fails or not. I hooked up to all the listeners available, but no message is sent back to the application. For the sake of completeness, this is how I'm configuring the `Socket` and `Channel`:

```haskell
socket = Phoenix.Socket.init "this is a wrong host on purpose"
        |> Phoenix.Socket.onClose (always Error)
        |> Phoenix.Socket.onNormalClose Error
        |> Phoenix.Socket.onAbnormalClose Error

channel = Phoenix.Channel.init "whatever:msg"
        |> Phoenix.Channel.onDisconnect Error
        |> Phoenix.Channel.onError Error
        |> Phoenix.Channel.onJoinError (always Error)
        |> Phoenix.Channel.onLeave (always Error)
        |> Phoenix.Channel.withDebug
```

The issue is that `Error` is never dispatched, although `withDebug` correctly shows `Channel "whatever:msg": Disconnected` so the event seems to be there but it's never sent back to the main Router.

Any help appreciated, thanks! :)

**Comment by cjen07** [comment]
I think you can use `onJoin`, https://saschatimme.github.io/elm-phoenix/channel.html#onJoin

**Comment by alpacaaa** [comment]
@cjen07 Not sure... I want to know when I get disconnected not when I join a channel.

**Comment by alpacaaa** [comment]
@cjen07 Not sure... I want to know when I get disconnected, how would `onJoin` help with that?

**Comment by cjen07** [comment]
@alpacaaa if the disconnect is caused by internet disconnection, i.e a user unpluges the internet, this user and users in the same channel will not receive any msg. I think there are two ways to fix it, the first is to use Presence, which is recommended, and the second is in this [post](http://stackoverflow.com/questions/33934029/how-to-detect-if-a-user-left-a-phoenix-channel-due-to-a-network-disconnect).

**Comment by cjen07** [comment]
and if the server is down and the internet is connected, onDisconnect will receive a msg.

**Comment by bigardone** [comment]
Hey, @alpacaaa did you finally managed to solve or handle the issue? I'm experiencing a very similar one... Thanks in advance :)

**Comment by alpacaaa** [comment]
@bigardone nope, I still have this issue. What @cjen07 points at is correct but, as far as I can tell, does not work when the channel is never joined – that is, the page loads and the socket server is down, no event gets dispatched. Maybe this is a better way of phrasing the problem?

**Comment by saschatimme** [comment]
I don't have much time to investigate, but I think the problem could be here https://github.com/saschatimme/elm-phoenix/blob/master/src/Phoenix.elm#L514.
Could you checkout the error code from the websocket connection? ([Here](https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent) is a list of the error codes).
There is also a `Socket.withDebug` method which should give you more information.

I hope this helps you to figure out what is wrong @bigardone @alpacaaa.

**Comment by alpacaaa** [comment]
`Phoenix.Socket.onAbnormalClose` works great! 🎉 🎉 🎉 

I thought I tested it with version `0.3.0` but that was not the case. Sorry about that :)

**Comment by saschatimme** [comment]
@bigardone does updating also solve your problem?

**Comment by bigardone** [comment]
@alpacaaa  @saschatimme first of all, thank you very much for your quick responses 😍 
The issue I'm having is that once the connection is made and the channel is joined, if I turn off the wifi it is not receiving any error or anything (not even the `onAbnormalClose`), until it reaches the socket timeout (which is set to 45 seconds). What I have done is creating a new out port which it is called as the `window.navigator.onLine` event handlers (https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/onLine), so it detects it immediately. Does it make sense?
