### ISSUE TITLE
Confused results when multiple sockets are active

### ISSUE THREAD

**Issue by markhamburg** [saschatimme/elm-phoenix#33]
Refs are managed per socket but the self callbacks dictionary is keyed only be the ref. This means that if one opens multiple sockets, the self callbacks dictionary can overwrite the handler for one push or join message with the handler for a push or join message on another socket. Much ugliness follows.

The fix for this appears to be to key the self callbacks dictionary by `(Ref, Endpoint)` instead of just `Ref`. Pull request coming.

**Comment by saschatimme** [comment]
I see the problem....
Not sure whether you can use a tuple as a dictionary key, so you would probably need to have nested dicts, i.e. first keyed `Endpoint` then by `Ref`.

**Comment by markhamburg** [comment]
Tuples of comparable items are comparable and hence are viable keys. It's
probably best to do it as (Ref, Endpoint) as opposed to (Endpoint, Ref)
because the refs are more likely to be different and hence the comparisons
will be ever so slightly faster on average.

Mark

**Comment by edennis** [comment]
@markhamburg I know it was a while ago, but I'd be interested in knowing if this PR (https://github.com/saschatimme/elm-phoenix/pull/40) fixes the problem you were having. I was able to reproduce it locally with a contrived example but it'd be nice to have some confirmation from a real-world use case.

**Comment by saschatimme** [comment]
#40 closed that
