### ISSUE TITLE
Easy way to leave a channel

### ISSUE THREAD

**Issue by praveenperera** [saschatimme/elm-phoenix#35]
First of all, thanks for this package its awesome and super intuitive to use.

I was wondering why there isn't a way in the library to leave a channel. I was wondering what the thought process behind not including it is.  And maybe if you don't think it belongs in the library we could add some documentation to show how to leave a channel by pushing the `"phx_leave"` message.

My particular use case involves where a user should only be in one channel at a time. If they join a new channel I would like them automatically leave the old channel. I'm doing this by saving the channelId in the model and using that in channel init. `Channel.init ("room:" ++ model.roomId)` 

And in the update function any branch that changes the channel also sends a Push of `"phx_leave"`. 

Does that make sense?

**Comment by saschatimme** [comment]
You leave a channel automatically if it isn't listed anymore.
Assume you have at one point in time
```elm
subscriptions model =
    Phoenix.connect socket [Channel.init "room1"]
```
If at the next tick you have
```elm
subscriptions model =
    Phoenix.connect socket [Channel.init "room2"]
```
the user will automatically leave `room1` and join `room2`. At least that it is the way it is intended to work 😅.

Does that work you?

**Comment by praveenperera** [comment]
Oh stupid me, I should have checked that first 🙈. It works great, sorry about that!
