### ISSUE TITLE
Reply messages

### ISSUE THREAD

**Issue by praveenperera** [saschatimme/elm-phoenix#36]
Is it possible to handle reply message after pushing a message? On the javascript client its done with the receive callback method.

```javascript
    channel.push("new_msg", {body: $chatInput.val()}).receive(
      "ok", (reply) => console.log("got reply", reply)
     )
```

**Comment by saschatimme** [comment]
I think [`Push.onOk`](https://saschatimme.github.io/elm-phoenix/push.html#onOk) is what you are looking for.

**Comment by praveenperera** [comment]
@saschatimme ah yes sorry I think you are right. Let me try it and can I do a PR to the docs to add the wording "reply", just because that's the wording used in phoenix and the other clients. Might make it easier for people to find.
