### ISSUE TITLE
No Msg if server denies socket connection

### ISSUE THREAD

**Issue by dustinfarris** [saschatimme/elm-phoenix#39]
If I use [Socket.withParams](https://saschatimme.github.io/elm-phoenix/socket.html#withParams) to send an authentication token, and the server 403s because the token is invalid, elm-phoenix does not have a way to send a Msg.  Its current behavior is to keep retrying the connection.

**Comment by saschatimme** [comment]
Can you take a look at the detailed description in [this PR](https://github.com/saschatimme/elm-phoenix/pull/10) and see if this resolves your problem?

**Comment by dustinfarris** [comment]
@saschatimme yes, it makes sense and explains why this doesn't exist.

It sounds like Phoenix should allow you to close the connection with customizable CloseEvent codes. 4000-4999 are reserved for this purpose, I believe.  If Phoenix does this, elm-phoenix could have a `onClose : (Int -> msg) -> Socket -> Socket` function.

I have started a discussion in phoenix-core: https://groups.google.com/forum/#!topic/phoenix-core/jceGwJRAfg0
