### ISSUE TITLE
Add the ability to add a new channel subscription after calling `connect`

### ISSUE THREAD

**Issue by Vynlar** [saschatimme/elm-phoenix#47]
I would like to be able to, after establishing a connection, mutate my connection to include additional channels. Is this possible already and I just haven't figured it out? Otherwise, I suggest the addition of a new function in the `Phoenix` module that allows for this behavior. Thoughts?

**Comment by saschatimme** [comment]
You can always join and leave additional channel by just declaring them in your subscription.

If you start with this
```elm
subscriptions model =
    Phoenix.connect socket [channel1]
```
and after some time you update the subscriptions to 
```elm
subscriptions model =
    Phoenix.connect socket [channel1, channel2]
```
Then you will automatically join channel2. And if you don't need the channel anymore you can just declare
```elm
subscriptions model =
    Phoenix.connect socket [channel1]
```
again and you will leave channel2.

**Comment by Vynlar** [comment]
@saschatimme Thank you! I didn't realize that subscribe was called on successive state changes. This is amazingly slick!
