### ISSUE TITLE
Adding Channel.map

### ISSUE THREAD

**Issue by lguminski** [saschatimme/elm-phoenix#8]
Unfortunately Elm doesn't come with a generic `map` function, and the lack of Channel.map doesn't allow to break code nicely into modules.

**Comment by saschatimme** [comment]
Just relased a new version with `Channel.map` and `Socket.map` exposed!

**Comment by lguminski** [comment]
Cool! Thanks!

**Comment by lguminski** [comment]
Works perfectly!
