### ISSUE TITLE
Reconnecting after browser refresh

### ISSUE THREAD

**Issue by puruzio** [saschatimme/elm-phoenix#9]
Thanks for this awesome library!

Can you please provide some direction on how to reconnect to the channel when the browser is refreshed?

For instance, in the elm-phoenix example, refreshing the browser after joining causes `no channel exists` message, and the `enterLeaveLobby` view indicates `User name already taken` if I attempt to join again with the same user name.

**Comment by saschatimme** [comment]
> Can you please provide some direction on how to reconnect to the channel when the browser is refreshed?

After a browser refresh the client code starts from scratch. So you have to store information about which channels you want to connect to in `LocalStorage`, `SessionStorage` or something like that. Then you can use this information on the start to setup the channels as before the browser refresh.

> For instance, in the elm-phoenix example, refreshing the browser after joining causes no channel exists message, and the enterLeaveLobby view indicates User name already taken if I attempt to join again with the same user name.

The example app had an error in the phoenix part which caused the `User name already taken` error. I just pushed a fix for that.

**Comment by puruzio** [comment]
Thank you!
